# Makefile for programs in directory 08-Abstract-Data-Types
# ***************************************************************

PROGRAMS = \
    driver-array \
    driver-list

# ***************************************************************
# Parameters to control Makefile operation
# Note that the gccx command script must be defined

#CC = gccx
#gcc -I..booklib  -o prog   prog.c  ../booklib/cslib.a
CC = gcc -I../booklib
CFLAGS = 

# ***************************************************************
# Entry to bring the package up to date

all: $(PROGRAMS)

# ***************************************************************
# Standard entries to remove files from the directories
#    tidy    -- eliminate unwanted files
#    scratch -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out graphics.ps

scratch: tidy
	rm -f *.o *.a $(PROGRAMS)

# ***************************************************************
# C compilations

driver.o: driver.c set.h
	$(CC) $(CFLAGS) -c driver.c

setArrayImp.o: setArrayImp.c set.h
	$(CC) $(CFLAGS) -c setArrayImp.c

setLinkedListImp.o: setLinkedListImp.c set.h
	$(CC) $(CFLAGS) -c setLinkedListImp.c

list.o: list.c list.h
	$(CC) $(CFLAGS) -c list.c

# ***************************************************************
# Executable programs

driver-array: driver.o setArrayImp.o
	$(CC) $(CFLAGS) -o driver-array driver.o setArrayImp.o ../booklib/cslib.a

driver-list: driver.o setLinkedListImp.o
	$(CC) $(CFLAGS) -o driver-list driver.o setLinkedListImp.o ../booklib/cslib.a
